# Generated by Django 4.2.7 on 2023-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
