# Generated by Django 4.2.7 on 2023-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_good_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
