# Generated by Django 3.2.23 on 2024-01-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0011_auto_20240111_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strength',
            options={'verbose_name': 'Крепость, %', 'verbose_name_plural': 'Классификатор крепостей'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Объем, л', 'verbose_name_plural': 'Классификатор объемов'},
        ),
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
