# Generated by Django 3.2.23 on 2024-01-17 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0012_auto_20240112_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Спиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='TypeOfFermentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип ферментации',
                'verbose_name_plural': 'Типы ферментации',
            },
        ),
        migrations.AlterModelOptions(
            name='strength',
            options={'ordering': ['value'], 'verbose_name': 'Крепость, %', 'verbose_name_plural': 'Классификатор крепостей'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['value'], 'verbose_name': 'Объем, л', 'verbose_name_plural': 'Классификатор объемов'},
        ),
        migrations.AddField(
            model_name='good',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.style', verbose_name='Стиль'),
        ),
        migrations.AddField(
            model_name='good',
            name='type_of_fermentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.typeoffermentation', verbose_name='Тип ферментации'),
        ),
    ]
