# Generated by Django 3.2.23 on 2024-01-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0014_auto_20240130_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, null=True, verbose_name='Значение'),
        ),
    ]
