# Generated by Django 3.2.23 on 2024-01-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0016_alter_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Классификатор стран мира'},
        ),
        migrations.AlterField(
            model_name='good',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Наименование полное'),
        ),
    ]
