# Generated by Django 3.2.23 on 2024-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0021_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_by'], 'verbose_name': 'Раздел каталога', 'verbose_name_plural': 'Разделы каталога'},
        ),
        migrations.AddField(
            model_name='category',
            name='order_by',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
