# Generated by Django 3.2.23 on 2024-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0026_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='country',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='filtering',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='gassing',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='good',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='pasteurization',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='strength',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='style',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='typeoffermentation',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='unit',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='volume',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Файл изображения 570х570'),
        ),
    ]
