# Generated by Django 3.2.23 on 2024-08-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0027_alter_category_image'),
        ('catalog_app', '0027_auto_20240820_0931'),
    ]

    operations = [
    ]
