# Generated by Django 3.2.23 on 2024-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0030_auto_20241014_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='show_price_by_liter',
            field=models.BooleanField(default=False, verbose_name='Показывать цену за литр'),
        ),
    ]
