# Generated by Django 3.2.23 on 2024-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0032_good_price_by_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='tags',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='trademark',
            name='tags',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, null=True, verbose_name='Теги'),
        ),
    ]
