# Generated by Django 3.2.23 on 2025-08-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0033_auto_20241026_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена за единицу (старая)'),
        ),
    ]
