# Generated by Django 3.2.23 on 2026-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0034_good_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
    ]
