# Generated by Django 3.2.23 on 2024-01-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
