# Generated by Django 3.2.23 on 2024-06-25 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_alter_image_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('order_by', models.SmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_app.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Карусель',
                'ordering': ['order_by'],
            },
        ),
    ]
