# Generated by Django 3.2.23 on 2024-06-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='order_by',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
