# Generated by Django 3.2.23 on 2024-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0006_alter_carousel_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/', verbose_name='Файл изображения'),
        ),
    ]
