# Generated by Django 3.2.23 on 2024-08-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0007_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['order_by'], 'verbose_name': 'Элемент 1200х680', 'verbose_name_plural': 'Карусель'},
        ),
    ]
