# Generated by Django 3.2.23 on 2024-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0007_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['order_by'], 'verbose_name': 'Элемент 1200х680', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='image',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
    ]
