# Generated by Django 3.2.23 on 2024-08-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0008_alter_carousel_options'),
        ('image_app', '0008_auto_20240820_0931'),
    ]

    operations = [
    ]
