# Generated by Django 3.2.23 on 2024-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0009_merge_20240820_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='marked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пометка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='marked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пометка'),
        ),
    ]
