# Generated by Django 3.2.23 on 2025-08-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0010_auto_20240828_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка'),
        ),
    ]
