# Generated by Django 4.2.7 on 2023-12-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_manufacturer_good_manufacturer'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good'),
        ),
    ]
