# Generated by Django 4.2.7 on 2023-12-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_order_author_alter_contract_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_app.contract', verbose_name='Договор'),
        ),
    ]
