# Generated by Django 4.2.7 on 2023-12-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_alter_good_slug'),
        ('order_app', '0008_alter_order_author_alter_order_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_app.order'),
        ),
    ]
