# Generated by Django 3.2.23 on 2024-03-31 03:56

from django.db import migrations, models
import django.db.models.deletion
import order_app.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("order_app", "0011_auto_20240103_1014"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=2,
                        null=True,
                        verbose_name="Значение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус заказ покупателя",
                "verbose_name_plural": "Статусы заказов покупателей",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=order_app.models.OrderStatus,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="order_app.orderstatus",
                verbose_name="Статус",
            ),
        ),
    ]
