# Generated by Django 3.2.23 on 2024-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='organization',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка'),
        ),
    ]
