# Generated by Django 3.2.23 on 2024-08-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_app", "0015_auto_20240820_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="marked",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Пометка"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="marked",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Пометка"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="order_app.orderstatus",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="marked",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Пометка"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="marked",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Пометка"
            ),
        ),
    ]
