# Generated by Django 4.2.7 on 2023-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$3XIVsmZRb3Ar5QFJoSPBkh$YR2KgAcsxA8O+oiEkEZ29+sS1qtpdlK8Z0DAgn4dG+I=', max_length=128, verbose_name='password'),
        ),
    ]
