# Generated by Django 4.2.7 on 2023-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$TRCjX9XpnzpXGJ01s601TP$eSrGdFrw/pEKmc8FIRmAM4mEpB3aXj3iKrLrdK+xY5k=', max_length=128, verbose_name='password'),
        ),
    ]
