# Generated by Django 4.2.7 on 2023-11-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$mMglNnXLdDwJrOHzmiY3X1$UvV6VR4WIZeHcWkS4TGnpm7LqJzRjm9t+yCH6cbmY+E=', max_length=128, verbose_name='password'),
        ),
    ]
