# Generated by Django 4.2.7 on 2023-12-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$9FN89OK8gwoPYRhDf62ikp$lP1aED42UpknofDDGFvSqcsSX3dee6+Swfps2Mzpjj8=', max_length=128, verbose_name='password'),
        ),
    ]
