# Generated by Django 4.2.7 on 2023-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Pin',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$IIh0qhVoPUSDqPR5IJMW8v$bca4JTIAHUWLQrLss98NY35gxmtGlpcvOBTooGwKgZs=', max_length=128, verbose_name='password'),
        ),
    ]
