# Generated by Django 4.2.7 on 2023-12-05 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('auth_app', '0006_rename_record_pin_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='client_app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$6may4gws3eO3LTpWPCR6mr$65SqstBbxusOfV7iEfZls4nd4IttsJ9JrWyf9kQdIUQ=', max_length=128, verbose_name='password'),
        ),
    ]
