# Generated by Django 4.2.7 on 2023-12-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_user_client_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$cot5Qf3XMB8JnP8xdfEJIl$PkiMNa+gTpliLUAjFNYR7u08C4blyXa1IW8tPrO4JsE=', max_length=128, verbose_name='password'),
        ),
    ]
