# Generated by Django 4.2.7 on 2023-12-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LF3Z7nq02bs2y54E2cyhD0$G2AZ75DH0f1/JFhbRIFD6uSttcG+VPUiMBHQM8aZ8Kc=', max_length=128, verbose_name='password'),
        ),
    ]
