# Generated by Django 4.2.7 on 2023-12-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LSpESpa4Oem6nPocdHpiK0$I3vu/duoXTbK5pGcLqGNZlVBZr+okjRqJHOSTXW9eN0=', max_length=128, verbose_name='password'),
        ),
    ]
