# Generated by Django 4.2.7 on 2023-12-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$M7bslkxmwpuErTs7yF0Ba7$ilgBTtvLaBgXYM5QL+UNCk5kOUuNatqZy2S6irsgXOE=', max_length=128, verbose_name='password'),
        ),
    ]
