# Generated by Django 4.2.7 on 2023-12-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$45KLlv6aJE7MNBkdFdnP3K$xdAejp46JPFo1UwvPG8YJ4xJS5kc3L+B6LyyxMaML5w=', max_length=128, verbose_name='password'),
        ),
    ]
