# Generated by Django 3.2.23 on 2023-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$o1HopALawJUdXpODbH3lQK$jePlaDsCaS/LTFPkPW2Ixid7Q656Hi2fELJsRiXQqyg=', max_length=128, verbose_name='password'),
        ),
    ]
