# Generated by Django 3.2.23 on 2023-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$WpWhe6Vy8TdVOp8Yfw4LCn$nckTUqdWxnAYQuk8b7KvyYBnwzRjDDsfUL1tsjbZLXI=', max_length=128, verbose_name='password'),
        ),
    ]
