# Generated by Django 3.2.23 on 2023-12-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$tkDevqfo5QYlSkgC99yYXg$Xt1iL0dTyXaibGnlMmYmTe3zp5ZTr5Ur1XU4kMfcv1o=', max_length=128, verbose_name='password'),
        ),
    ]
