# Generated by Django 3.2.23 on 2023-12-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$u2sxx2hnJdebt4hG4FpL2v$TFJnexyoCCGvD+yBb1N+Rz31QbvkDsg5v2oHMp6GVr8=', max_length=128, verbose_name='password'),
        ),
    ]
