# Generated by Django 3.2.23 on 2024-01-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$TNT8hV9fEFpeB8DzLn3Dm6$tRRqpo5i2JQPVA++4KKASO3twt1bQ3eCUyZbyUUqsRA=', max_length=128, verbose_name='password'),
        ),
    ]
