# Generated by Django 3.2.23 on 2024-01-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$sCrpTa1VbHoUStLvQPxL2o$xN4fd2IIxbBbPJohBi4yxtTe2tgHVn+cshWL/Fe5ssM=', max_length=128, verbose_name='password'),
        ),
    ]
