# Generated by Django 3.2.23 on 2024-01-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$cMS1Od2uaeNeKciXfC2sq8$tkaIVdlpcRxml/yff6El7kTdUujGNq+X5EAet20Loio=', max_length=128, verbose_name='password'),
        ),
    ]
