# Generated by Django 3.2.23 on 2024-01-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ScDcwczi6SMVb2x6f8p2NG$thYTw6SbNmIV+WUn9Fx2zapTdhbLWSmSLKjDg16lLQ8=', max_length=128, verbose_name='password'),
        ),
    ]
