# Generated by Django 3.2.23 on 2024-01-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$gdQSH3fzSVGLkW4IGArZxe$zHLgNfhtldRtR8Vt3LDjodq095sKCgT+FZ43BbFBkpY=', max_length=128, verbose_name='password'),
        ),
    ]
