# Generated by Django 3.2.23 on 2024-01-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$H1Ygdh1bRD8BDc2sVNgYj2$h12w0e3XneyQ/M8hXklQBjPppWsrrTSkp80CyR1/iHI=', max_length=128, verbose_name='password'),
        ),
    ]
