# Generated by Django 3.2.23 on 2024-02-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ZFy3wgxGhB3Oi6fqiROPbX$MJjniIqdV/omw0ojwIjMfXvhGfGzk5fmGQ2RPEyYoNk=', max_length=128, verbose_name='password'),
        ),
    ]
