# Generated by Django 3.2.23 on 2024-03-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_auto_20240228_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$HjBU0pO7mlRkirzvVD529p$zLf7lMZ1PjVwJh+bTS8FQSs9cIAZxPYhMGcyQ7o/qgQ=', max_length=128, verbose_name='password'),
        ),
    ]
