# Generated by Django 3.2.23 on 2024-03-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$QQ3gQUDcOTuoyXIUNMvzkC$/S4L9SKbehExhF/TYpdl8ct7wJwHCSGt7Z31VfO2lj4=', max_length=128, verbose_name='password'),
        ),
    ]
