# Generated by Django 3.2.23 on 2024-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ettrBzh1aCyCTcqK0HlDYm$eZBpuZFOzTf+ATTUbBtLn2uyVZEac5lpEWvRL1otGLE=', max_length=128, verbose_name='password'),
        ),
    ]
