# Generated by Django 3.2.23 on 2024-06-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$sEsqSL0nzdzgFOONWZPnL8$zvvyqnvLEacJOWSPd6UEPbZDIVAj1RC8tOR8sneEFv4=', max_length=128, verbose_name='password'),
        ),
    ]
