# Generated by Django 3.2.23 on 2024-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$gnqUPRpDDoTLC6zEIqD6dQ$kHsnbfi/0LZ834/2e7LbcT2ZOsS7uFaMy7/X2R1lmh4=', max_length=128, verbose_name='password'),
        ),
    ]
