# Generated by Django 3.2.23 on 2024-06-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$N3nFaXeqUVQ7xztH6Igbfj$7xK0kDrnvm0gawcMrT0fhsKF1WDirMEEZ5XQLefYBKQ=', max_length=128, verbose_name='password'),
        ),
    ]
