# Generated by Django 3.2.23 on 2024-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0033_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$3dRisokM03LTAh98jMOA9a$Z5krAfiwN2AhtVuaXKROUOAg+qJ3sJliyO4h+2PPIvs=', max_length=128, verbose_name='password'),
        ),
    ]
