# Generated by Django 3.2.23 on 2024-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$E3CCG8LEbQxz3vXs9MSP7H$NOvYJ9fmx4t8cbagfacOJmuQ7eyrObcAOy7JvKgOJD0=', max_length=128, verbose_name='password'),
        ),
    ]
