# Generated by Django 3.2.23 on 2024-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$3dLjDSQygTKlW58tmO5dvq$4hGLJmv0zSK0Z4LanyyJfJU6yHPfa5cjBGQRIs14r/k=', max_length=128, verbose_name='password'),
        ),
    ]
