# Generated by Django 3.2.23 on 2024-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0037_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$ew4KRVULPVr7KP1qHntmEe$k3MUR+FRMkg8Wt1Yx26/mg8v5Dm107/b4tgt32+dQMA=', max_length=128, verbose_name='password'),
        ),
    ]
