# Generated by Django 3.2.23 on 2024-06-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$4CXQCjJMvMDul7sKEKr1JC$3i2wIn6TXB6+RV5v2j7cNug2RbU+/e/lQmEUNJnRDxQ=', max_length=128, verbose_name='password'),
        ),
    ]
