# Generated by Django 3.2.23 on 2024-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$6IpWELrirOMCBbwxky9u5E$qT0yYOfOxtdHlAcGkHfUsVBKl2ZOUNKsL5mGEZNfSqo=', max_length=128, verbose_name='password'),
        ),
    ]
