# Generated by Django 3.2.23 on 2024-07-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0042_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$z0s0UqkG1wwVGfXzfLh79j$vwOcm81bv9rVZMmWEJQi5R3rNKduKOiKnbG5gCqjbC0=', max_length=128, verbose_name='password'),
        ),
    ]
