# Generated by Django 3.2.23 on 2024-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0043_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$PuGAgIS3WFfMCjaqgeIonK$ka3A1ZQBk1qC+7WRXGwMvsNSu+p8PxbRwZCXVCmMUYo=', max_length=128, verbose_name='password'),
        ),
    ]
