# Generated by Django 3.2.23 on 2024-07-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0044_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$1m1naB7IPNaLwDZJbGT832$T5ZTklIt/1ddIg69UZd2mBeHFv37+weOY4HqdvrSq24=', max_length=128, verbose_name='password'),
        ),
    ]
