# Generated by Django 3.2.23 on 2024-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0045_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$u5mRvPP5ObCtXhiSsOLMaX$4kOZ9tlmxotXGYd+8sg9zOwVii052CIsFvi7Wucg2iw=', max_length=128, verbose_name='password'),
        ),
    ]
