# Generated by Django 3.2.23 on 2024-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0046_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$GCqgMnaNLDCsmlLpFn7uUN$RMGNwxb2fnGXutuGMUy3eiZv1CQ2tM8XIFQss4jcPqI=', max_length=128, verbose_name='password'),
        ),
    ]
