# Generated by Django 3.2.23 on 2024-08-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0048_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$EdZrLyJgpUT75afIkX5Rdk$TtQmPJT4dzeR2pJk6IWFoOPg0Ir2xThK+nikkQTi7qQ=', max_length=128, verbose_name='password'),
        ),
    ]
