# Generated by Django 3.2.23 on 2024-08-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0049_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$nOpDcZDaf8He26Rmb3oHlO$wrWzNU09aOGcKbIEye89waOqT18ZeJKRPzFgLo8wK/8=', max_length=128, verbose_name='password'),
        ),
    ]
