# Generated by Django 3.2.23 on 2024-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0050_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$XUBLiGfOBygmkJAyHZ9Zku$W4HT2fxJTM3JW5n7Whw+NHIAJSC9xBG03Lj1fPHD26A=', max_length=128, verbose_name='password'),
        ),
    ]
