# Generated by Django 3.2.23 on 2024-10-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0051_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$qvEqKDvOggypec7OlvzEyG$4AcA6JBxxaXdbweKIXfeoncSqEQ5OsTVtRzNI3/JYgg=', max_length=128, verbose_name='password'),
        ),
    ]
