# Generated by Django 3.2.23 on 2024-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0053_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$AF6QBTkjiW6dCUyujzDqMZ$r7sfzNF3IGe/bS4omel6XGElYjoxZcEJeRJR2jJxC9E=', max_length=128, verbose_name='password'),
        ),
    ]
