# Generated by Django 3.2.23 on 2024-10-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0055_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$oI9lVlohrcjXIyIJCIkz7g$EcsNeG1FZPZ+Lv4X7V1TJB7AnCSi3JN5CnB2ZhlBt1k=', max_length=128, verbose_name='password'),
        ),
    ]
