# Generated by Django 3.2.23 on 2024-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0056_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$GQK1J3OLpwpBmLj1Zb0JR0$3Jmh5znN1OnoOuj+AVSQqlVsln3WMY0dDzLI+JthVdA=', max_length=128, verbose_name='password'),
        ),
    ]
