# Generated by Django 3.2.23 on 2025-08-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0057_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$Xfcqh94emrKqrnwO3KGHuM$Wk3Lk6hZI4Xmzb3dzseCY+pk+/YbtJP6tnNYNdO05Gw=', max_length=128, verbose_name='password'),
        ),
    ]
