# Generated by Django 3.2.23 on 2025-08-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0058_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$SpgjaTQczGaizyQHAWYB0C$9eyK9dEm6piBUot5Gmg++rccuXCMe3UuxYm/bt9eEEI=', max_length=128, verbose_name='password'),
        ),
    ]
