# Generated by Django 3.2.23 on 2026-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0059_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$Ye1v2OuQ9wm5v4Ios2D475$dz+/S3GkOgMa2y+oLNTIfoBYaCpRSCzCXpSRZDafzOs=', max_length=128, verbose_name='password'),
        ),
    ]
