# Generated by Django 3.2.23 on 2024-08-20 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('marked', models.BooleanField(blank=True, default=True, null=True, verbose_name='Пометка')),
                ('type', models.CharField(choices=[('PH', 'phone'), ('EM', 'email')], default='PH', max_length=150, verbose_name='Тип')),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Контактная информация для информирования',
            },
        ),
    ]
