# Generated by Django 3.2.23 on 2024-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='marked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пометка'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='type',
            field=models.CharField(choices=[('PH', 'Телефон'), ('EM', 'Почта')], default='PH', max_length=150, verbose_name='Тип'),
        ),
    ]
