# Generated by Django 3.2.23 on 2024-07-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Point',
        ),
    ]
