# Generated by Django 3.2.23 on 2024-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_auto_20240820_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='marked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пометка'),
        ),
        migrations.AlterField(
            model_name='point',
            name='marked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пометка'),
        ),
    ]
